version: '3.3'
networks:
  wln_network:
     external: true

services:
   nginx:
      container_name: nginx_proxy
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
      volumes:
        #- ./node.conf:/etc/nginx/conf.d/node.conf
        - ./node.conf:/etc/nginx/conf.d/default.conf
      networks:
       - wln_network
