FROM alpine:latest

RUN apk update && apk add --no-cache \
    apache2 \
    php \
    php-apache2 \
    php-mysqli \
    php-json \
    php-openssl \
    php-curl \
    php-zlib \
    php-xml \
    php-phar \
    php-mbstring \
    php-gd \
    php-session \
    php-dom \
    php-ctype \
    php-simplexml


RUN rm /var/www/localhost/htdocs/index.html
COPY . /var/www/localhost/htdocs/

RUN chown -R apache:apache /var/www/localhost/htdocs/
RUN chmod 755 -R /var/www/localhost/htdocs/

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
